spring:
  application:
    name: demo-springboot4
  validation:
    use-lombok-nonnull: true
bcnpj:
  base:
    url: ${env:bcnpj_url}
  credentials:
    username: ${env:bcnpj_username}
    password: ${env:bcnpj_password}


