spring:
  application:
    name: demo-springboot4
  validation:
    use-lombok-nonnull: true
ibge:
  base:
    url: https://servicodados.ibge.gov.br
bcnpj:
  base:
    url: https://b-cnpj.camara.leg.br
