spring:
  application:
    name: demo-springboot4
  validation:
    use-lombok-nonnull: true
ibge:
  base:
    url: https://servicodados.ibge.gov.br
bcnpj:
  base:
    url: ${bcnpj_url}
  credentials:
    username: ${bcnpj_username}
    password: ${bcnpj_password}


