# Configurações padrão
spring:
  application:
    name: demo-springboot4
  mvc:
    apiversion:
      supported: 1.0.0,2.0.0
      default: 2.0.0
      use:
        header: X-Version
  output:
    ansi:
      enabled: ALWAYS
  validation:
    use-lombok-nonnull: true
bcnpj:
  base:
    url: ${env:bcnpj_url}
  credentials:
    username: ${env:bcnpj_username}
    password: ${env:bcnpj_password}
bcpf:
  base:
    url: ${env:bcpf_url}
  credentials:
    username: ${env:bcpf_username}
    password: ${env:bcpf_password}
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5level) %clr(--){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
