spring:
  application:
    name: demo-springboot4
  validation:
    use-lombok-nonnull: true
ibge:
  base:
    url: https://servicodados.ibge.gov.br
bcnpj:
  base:
    url: 
  credentials:
    username: 
    password: 


